"""
main.py

Orchestration and UI layer for the TechStore AI Customer Support
Assistant using the OpenAI Agents SDK.

Architecture:

    Gradio UI
        |
        v
    Triage Agent
        |
        +-------------------+-------------------+
        |                   |                   |
        v                   v                   v
    Order & Product     Support Agent      Knowledge Agent
        |                   |                   |
        v                   v                   v
      Tools               Tools               Tool

Agent definitions and handoffs live in agent_team.py.
Business logic lives in tools.py.
RAG functionality lives in rag.py.
UI theme, CSS, and assets live in ui_config.py.
"""

import asyncio
import logging
import os
import time
from datetime import date

import gradio as gr
from agents import Runner
from dotenv import load_dotenv

from agent_team import triage_agent
from ui_config import (
    BOT_AVATAR_PATH,
    CUSTOM_CSS,
    CUSTOM_THEME,
    USER_AVATAR_PATH,
)


# =====================================================================
# LOGGING
# =====================================================================

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
)

logger = logging.getLogger(__name__)


# =====================================================================
# ENVIRONMENT SETUP
# =====================================================================

load_dotenv()

OPENAI_API_KEY_ENV = "OPENAI_API_KEY"


def validate_environment() -> None:
    """
    Validate that the required environment variables are available.
    """

    api_key = os.environ.get(OPENAI_API_KEY_ENV)

    if not api_key:
        raise ValueError(
            f"{OPENAI_API_KEY_ENV} is not set. "
            "Add it to your .env file before running this application."
        )


validate_environment()


# =====================================================================
# DATE CONTEXT
# =====================================================================

def build_date_context() -> str:
    """
    Build a short context string containing today's actual date.
    """

    today_str = date.today().strftime(
        "%A, %B %d, %Y"
    )

    return f"Today's date is {today_str}."


# =====================================================================
# AGENT WORKFLOW LOGGING
# =====================================================================

def log_agent_workflow(result) -> None:
    """
    Print a concise summary of the agents involved in the current run.

    Example:

        [AGENT WORKFLOW] Triage Agent -> Order & Product Agent

    Or, if multiple agents are involved:

        [AGENT WORKFLOW] Triage Agent -> Knowledge Agent -> Order & Product Agent
    """

    agents_used = []

    for item in result.new_items:
        agent = getattr(
            item,
            "agent",
            None,
        )

        if agent and agent.name not in agents_used:
            agents_used.append(
                agent.name
            )

    if agents_used:
        print(
            f"[AGENT WORKFLOW] "
            f"{' -> '.join(agents_used)}"
        )


# =====================================================================
# AGENT RUNNER
# =====================================================================

async def run_agent_team(
    user_message: str,
    history: list[dict],
) -> str:
    """
    Run one turn through the multi-agent TechStore support team.

    The Triage Agent is the starting point and decides which specialist
    agent should handle the customer's request.

    Args:
        user_message:
            The latest customer message.

        history:
            Previous conversation messages managed by Gradio.

    Returns:
        The final response generated by the agent team.
    """

    # ---------------------------------------------------------------
    # BUILD CONVERSATION HISTORY
    # ---------------------------------------------------------------

    input_items = []

    for message in history:
        role = message.get("role")
        content = message.get("content")

        if role and content:
            input_items.append(
                {
                    "role": role,
                    "content": content,
                }
            )

    # ---------------------------------------------------------------
    # ADD CURRENT USER MESSAGE
    # ---------------------------------------------------------------

    current_user_input = (
        f"{build_date_context()}\n\n"
        f"Customer's latest message:\n"
        f"{user_message}"
    )

    input_items.append(
        {
            "role": "user",
            "content": current_user_input,
        }
    )

    # ---------------------------------------------------------------
    # RUN AGENT WORKFLOW
    # ---------------------------------------------------------------

    result = await Runner.run(
        triage_agent,
        input=input_items,
    )

    # ---------------------------------------------------------------
    # LOG AGENTS INVOLVED
    # ---------------------------------------------------------------

    log_agent_workflow(result)

    # ---------------------------------------------------------------
    # RETURN FINAL RESPONSE
    # ---------------------------------------------------------------

    if result.final_output is None:
        return (
            "I'm sorry, but I wasn't able to generate "
            "a response right now. Please try again."
        )

    return str(
        result.final_output
    )


# =====================================================================
# SYNCHRONOUS ADAPTER
# =====================================================================

def get_assistant_response(
    user_message: str,
    history: list[dict],
) -> str:
    """
    Bridge the synchronous Gradio function with the asynchronous
    Agents SDK runner.
    """

    return asyncio.run(
        run_agent_team(
            user_message=user_message,
            history=history,
        )
    )


# =====================================================================
# GRADIO CHAT FUNCTION
# =====================================================================

def chat_function(
    message: str,
    history: list[dict],
):
    """
    Adapter between Gradio and the multi-agent system.

    Workflow:

        Gradio
            |
            v
        Triage Agent
            |
            v
        Specialist Agent
            |
            v
        Tools
            |
            v
        Final Response
    """

    try:

        full_reply = get_assistant_response(
            user_message=message,
            history=history,
        )

    except Exception as error:

        logger.exception(
            "Agent team execution failed: %s",
            error,
        )

        full_reply = (
            "I'm sorry, but I encountered an error "
            "while processing your request. "
            "Please try again."
        )

    # ---------------------------------------------------------------
    # TYPING EFFECT
    # ---------------------------------------------------------------

    CHUNK_SIZE = 3
    TYPING_DELAY_SECONDS = 0.012

    for position in range(
        0,
        len(full_reply),
        CHUNK_SIZE,
    ):
        revealed_text = full_reply[
            : position + CHUNK_SIZE
        ]

        yield revealed_text

        time.sleep(
            TYPING_DELAY_SECONDS
        )

    # Make sure the complete response is returned.
    yield full_reply


# =====================================================================
# GRADIO INTERFACE
# =====================================================================

def build_interface() -> gr.ChatInterface:
    """
    Build the Gradio ChatInterface.

    UI styling, theme configuration, and asset paths are imported
    from ui_config.py.
    """

    styled_chatbot = gr.Chatbot(
        avatar_images=(
            USER_AVATAR_PATH,
            BOT_AVATAR_PATH,
        ),
        elem_classes=[
            "techstore-chatbot",
        ],
    )

    return gr.ChatInterface(
        fn=chat_function,
        chatbot=styled_chatbot,
        fill_height=True,
        title=(
            "TechStore AI Customer "
            "Support Assistant"
        ),
        description=(
            "Ask about order status, "
            "product availability, "
            "cancellations, refund eligibility, "
            "or support tickets. "
            "If I can't resolve your issue, "
            "I'll escalate it to our human "
            "support team."
        ),
        examples=[
            "What's the status of order 1001?",
            "Do you have any laptops in stock?",
            "What is your return policy?",
            "Am I eligible for a refund on order 1003?",
        ],
    )


# =====================================================================
# APPLICATION ENTRY POINT
# =====================================================================

if __name__ == "__main__":

    logger.info(
        "Starting TechStore AI Customer Support."
    )

    logger.info(
        "Agentic architecture enabled."
    )

    logger.info(
        "Starting agent: %s",
        triage_agent.name,
    )

    interface = build_interface()

    interface.launch(
        share=True,
        theme=CUSTOM_THEME,
        css=CUSTOM_CSS,
    )